version: '3' # composeファイルのバーション指定
services:
  app: # service名
    build: Docker/app/ # ビルドに使用するDockerfileがあるディレクトリ指定
    command: go run main.go
    env_file: .env
    ports:
      - ${APP_PORT}
    volumes:
      - .:/go/src/work # マウントディレクトリ指定
    depends_on:
      - db
  db: # データベース
    build: Docker/db/
    ports:
      - ${DB_PORT}
    volumes:
      # ここに永続化を書く
      - "./Docker/db/data:/data/db"
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      #- "./Docker/db/sql:/docker-entrypoint-initdb.d"
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      TZ: ${TZ}
      command: mongod --auth
