version: '3' # composeファイルのバーション指定
services:
  app: # service名
    build: . # ビルドに使用するDockerfileがあるディレクトリ指定
    command: go run main.go
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/work # マウントディレクトリ指定